apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rook-ceph-ingressgateway-certs
  namespace: rook-ceph
spec:
  secretName: rook-ceph-ingressgateway-certs
  issuerRef:
    name: gateways-issuer
    kind: ClusterIssuer
  commonName: rook-ceph.localhost.localdomain
  dnsNames:
    - rook-ceph.localhost.localdomain
