kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  creationTimestamp: null
spec:
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
      creationTimestamp: null
    data: null
  encryptedData:
    admin-password: AgB7HXG/KP2hfrO6DQczJ8j23or2I6tKO7vsvesLtQ1T40uyGfrrgbKuao7ooE4MEB1Q2kJwOuJD6UbOM81Z7L9U+HKqkTZkc8/H23AKpry/8hIiFDgmClYaWsltn9LaGp+INiASWHydEw5v6aCz1mqoDO78Cdu8afXkfs19p09gqgsU8mPVoHuXsvp21HwuCEEFb3WzIOBIlbw7YoipVCdW6orJSbs5+l9HqBuiibtCZEXY+p5rmMq48vqkJJ4bRKtEBtX+vxEp9SzVcJ5N+7Y37BsxbW9QD64///Lg67fmZGtK9w314GKpzYUDg18hMS+dEwdch7iHqwDZgyKx2zNyxPQmh5L5TcF685T+BrAKO/ld2+TV4pvOtoagxPgAwHrSi1YlXd/BYkT+G8oVAUX53I5C9VZljspNLDGbpP+thTzpjG4W5eXzc9IKiZ0oEK31U2lxX+AULVn7IWnYqHGaZ/9EQ6R7ack5Ox6YDzl/LtwktVzP217xnr9u3CTGdxr4xs4/NSKG5+UP65/PjYudVC5FYkkLDxM7T0c49E7rIxeO1dVkb1CPosSBnldFEJwIOXUSJKZfSwniyJfFnaZP2TwHdL6vCTKhVAcvUX0tLWM8QBgOV7Bf7yuxpYrl+GTUHaaX218Zat360rB0esDHkk+J+aaN4Dy1GY96mkA76CUhbqsO+ypPwfk4wnrH1D24ks6EigBDHw==
    admin-user: AgAqFFvCjCG0itAjJ1I1GaoeNZCNw47pyJZXp4eDP4RrVU9j2gEhvvHhuaR5e8g9ijWD69h5rioLnG2VatbfjK+aafRTzc2hJVDv63CEHOGUF3PmIMDoBuI+guT27q3Vw5JClDqqV5c6sdMjYY7bhQ/S0OfdvBn3ntVXQ4krF6+KRNuOcpXv1w2YTugMVqTNsOK94X6QdsElrJd2tsi+jjOmgff13YfzzSeoRqQV6DBeMED+hKUReE3ryE3nCTciTH6onM8sSRYeoxoGjz9mFpGuAl8OE6yumb/fHCG0y7vquMQxEsqItAZNhdM1pQk2Davg9dZk3+hpuQlxfMx2kssWpn5kWUt42+jgSu5awrOESMAYne6njuJKEM8pn31vR+z+AVqZbB3MbU9AvCDv99awfsL1WP8MxRLA6o7GSXfVYW1EHnQXLSBt5OJF4UkorO3DV7BNDVhbAaLwhT8ioImA57ipahaxwqb8FtdVhoq+5WFrrqz54qzZ0C2ycnti0v20CnQciga1FwNmfmM4nBkkzIuvb0TTra6yd3lFsuYISXUSpmXZXS/E29JFlbOxqtjYp2Pm17zGX1fkSp4NEIpbu/gg3n6tzyT5WIim5LSvnRYd2Fb/6Fhqwlr/xCexXKrH/wVJhIErLZh7uz8euvJ2o8tHvRFD9eDDRjlwtbgVf3bs2nyYWSb23lwARMPiE1yiVnr9
